# Generated by Django 4.0.3 on 2022-04-03 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasesACocher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='', max_length=150)),
                ('explicatif', models.TextField(blank=True, default='')),
                ('obligatoire', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': ' Cases à cocher',
                'ordering': ['ordre', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('introduction', models.TextField(blank=True, default='')),
                ('commentaire', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '  Étapes',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(default='', max_length=300)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('casesacocher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='sondage.casesacocher')),
            ],
            options={
                'ordering': ['casesacocher', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='ReponseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.anonyme')),
                ('options', models.ManyToManyField(to='sondage.option')),
            ],
        ),
        migrations.AddConstraint(
            model_name='etape',
            constraint=models.UniqueConstraint(fields=('numero',), name='numero_etape_unique'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='anonyme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.anonyme'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='etape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sondage.etape'),
        ),
        migrations.AddField(
            model_name='casesacocher',
            name='etape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casesacochers', to='sondage.etape'),
        ),
        migrations.AddConstraint(
            model_name='reponseoption',
            constraint=models.UniqueConstraint(fields=('anonyme',), name='reponse_option_cle_primaire'),
        ),
        migrations.AddConstraint(
            model_name='commentaire',
            constraint=models.UniqueConstraint(fields=('etape', 'anonyme'), name='commentaire_cle_primaire'),
        ),
        migrations.AddConstraint(
            model_name='casesacocher',
            constraint=models.UniqueConstraint(fields=('titre', 'etape'), name='nom_casesacocher_unique'),
        ),
    ]
