# Generated by Django 4.0.3 on 2022-04-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='avertissement_debut',
            field=models.TextField(default='\n<p>Merci de prendre le temps de répondre à ce sondage.\n  Celui-ci est organisé en plusieurs étapes. Pour chacune d\'entre elles, vous trouverez un\n  ou plusieurs jeux de cases à cocher, de boutons radio et, éventuellement, une zone de commentaire libre.\n  Si vous utilisez cette dernière, soyez vigilant à ne pas donner d\'information permettant de vous identifier\n  (sauf s\'il vous est indifférent de l\'être).</p>\n<p>Pour un jeu de cases à cocher, vous pourrez cocher autant de cases que vous le souhaitez.<br>\n  Pour un jeu de boutons radio, vous devrez cocher une et une seule case.\n</p>\n<p>Cliquez sur "Enregistrer" pour enregistrer vos réponses et passer à l\'étape suivante. Cliquez sur "Étape précédente"\n  pour revenir à l\'étape précédente.\n</p>\n<p>L\'anonymat de vos réponses est garanti. En vous déconnectant,\n  à la fin du sondage, vous supprimerez tout lien entre\nvotre compte nominatif et votre compte anonyme. Celui-ci ne peut, techniquement,\nêtre rétabli que par vous-même lors d\'une connexion ultérieure.</p>\n'),
        ),
        migrations.AlterField(
            model_name='administration',
            name='nom',
            field=models.CharField(default='Sondage Anonyme', max_length=150),
        ),
    ]
