# Generated by Django 4.0.3 on 2022-04-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0002_alter_administration_avertissement_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='admin_stats',
            field=models.BooleanField(default=False),
        ),
    ]
